corefit/urls.py
"""
Definition of urls for corefit.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views
from django.contrib.auth.views import login

import app.forms
import app.views

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
#from django.contrib import admin
#admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^$', login, {'template_name': 'home/login.html'}),
    url(r'^home/', include('home.urls')),
    url(r'^presenca/', include('presenca.urls')),
    url(r'^paciente/', include('paciente.urls')),
    url(r'^outros/', include('outro.urls')),
    url(r'^caixa/', include('caixa.urls')),
    url(r'^plano/', include('plano.urls')),
    url(r'^conta/', include('conta.urls')),
    url(r'^agenda/', include('agenda.urls')),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about', app.views.about, name='about'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #url(r'^admin/', include(admin.site.urls)),
]

home/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.home),
    ]

outro/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.outro),
    url(r'^balanco', views.balanco),
    url(r'^anual', views.anual),
    url(r'^trimestral', views.trimestral),
    url(r'^mensal', views.mensal),
    url(r'^diario', views.diario),
    url(r'^profissionais', views.prof),
    url(r'^novo_prof', views.novo_prof),
    url(r'^editar_prof', views.editar_prof),
    url(r'^salvar', views.salvar),
    ]

caixa/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class caixa_geral(models.Model):
    TIPO = (
        ('1', 'Entrada'),
        ('2', 'Saida'),
    )
    id = models.AutoField(primary_key=True)
    tipo = models.CharField(max_length=1, choices=TIPO)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    desc = models.CharField(max_length=200)
    data = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return self.tipo

outro/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class professor(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=200)
    telefone = models.CharField(max_length=20, null=True, blank=True)
    celular = models.CharField(max_length=20, null=True, blank=True)
    data_nasc = models.DateField(default=timezone.now)

   

outro/views.py
from django.shortcuts import render
from caixa.models import caixa_geral
from .models import professor
from django.utils import timezone
from datetime import timedelta
# Create your views here.
def outro(request):
    if request.user.is_authenticated():
        return render(request, 'outro.html', {'title':'Outros'})
    else:
        return render(request, 'home/erro.html', {'title':'Erro'})

def prof(request):
    if request.user.is_authenticated():
        return render(request, 'prof/prof.html', {'title':'Profissionais'})
    else:
        return render(request, 'home/erro.html', {'title':'Erro'})

def novo_prof(request):
    if request.user.is_authenticated():
        if request.method == 'POST' and request.POST.get('nome') != None:
            nome = request.POST.get('nome') 
            tel = request.POST.get('tel') 
            cel = request.POST.get('cel') 
            data_nasc = request.POST.get('data_nasc') 
            novo_prof = professor(nome=nome, telefone=tel, celular=cel, data_nasc=data_nasc)
            novo_prof.save()
            msg = "Novo profissional salvo com sucesso."
            return render(request, 'home/home.html', {'title':'Home', 'msg':msg})
        return render(request, 'prof/novo_prof.html', {'title':'Novo Profissional'})
    else:
        return render(request, 'home/erro.html', {'title':'Erro'})

def editar_prof(request):
    if request.user.is_authenticated():
        profs = professor.objects.all().order_by('nome')
        if request.method == 'POST' and request.POST.get('prof_id') != None:
            prof_id = request.POST.get('prof_id')
            prof = professor.objects.filter(id=prof_id).get()
            return render(request, 'prof/editar_prof.html', {'title':'Editar Profissional', 'prof':prof})
        return render(request, 'prof/busca_prof.html', {'title':'Editar Profissional', 'profs':profs})
    else:
        return render(request, 'home/erro.html', {'title':'Erro'})

def salvar(request):
    if request.user.is_authenticated():
        if request.method == 'POST' and request.POST.get('prof_id') != None:
            prof_id = request.POST.get('prof_id')
            prof = professor.objects.filter(id=prof_id).get()
            nome = request.POST.get('nome') 
            tel = request.POST.get('tel') 
            cel = request.POST.get('cel') 
            data_nasc1 = request.POST.get('data') 
            if nome != None:
                prof.nome = nome
            if tel != None:
                prof.telefone = tel
            if cel != None:
                prof.celular = cel
            if data_nasc1 == None or data_nasc1 == "":
                prof.data_nasc = prof.data_nasc
            else:
                prof.data_nasc = data_nasc1
            prof.save()
            msg = "Novo profissional editado com sucesso."
            return render(request, 'home/home.html', {'title':'Home', 'msg':msg})
        return render(request, 'prof/novo_prof.html', {'title':'Novo Profissional'})
    else:
        return render(request, 'home/erro.html', {'title':'Erro'})

def balanco(request):
    if request.user.is_authenticated():
        return render(request, 'balanco.html', {'title':'Balanco'})
    else:
        return render(request, 'home/erro.html', {'title':'Erro'})

def anual(request):
    if request.user.is_authenticated():
        return render(request, 'anual.html', {'title':'Balanco Anual'})
    else:
        return render(request, 'home/erro.html', {'title':'Erro'})

def trimestral(request):
    if request.user.is_authenticated():
        return render(request, 'trimestral.html', {'title':'Balanco Trimestral'})
    else:
        return render(request, 'home/erro.html', {'title':'Erro'})

def mensal(request):
    if request.user.is_authenticated():
        mes = timezone.now().strftime('%m')
        fat = 0
        luc = 0
        cus = 0
        for f in caixa_geral.objects.filter(data__month=mes, tipo=1).all():
            fat = fat + f.total
        for c in caixa_geral.objects.filter(data__month=mes, tipo=2).all():
            cus = cus + c.total
        luc = fat + cus
        return render(request, 'mensal.html', {'title':'Balanco Mensal', 'fat':fat, 'cus':cus, 'luc':luc})
    else:
        return render(request, 'home/erro.html', {'title':'Erro'})

def diario(request):
    if request.user.is_authenticated():
        hoje = timezone.now().strftime('%Y-%m-%d')
        caixas = caixa_geral.objects.filter(data__contains=hoje).all()
        if request.method == 'POST' and request.POST.get('data') != None:
            data1 = request.POST.get('data')
            caixas = caixa_geral.objects.filter(data__icontains=data1)
            return render(request, 'diario.html', {'title':'Extrato', 'caixas':caixas, 'hoje':data1})   
        return render(request, 'diario.html', {'title':'Balanco Diario', 'caixas':caixas, 'hoje':hoje})
    else:
        return render(request, 'home/erro.html', {'title':'Erro'})

outro/templates/anual.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar menu-lateral">
            <ul class="nav nav-pills flex-column">
                <li class="nav-item">
                    <a class="nav-link " href="/outros" style="color: #599a80;">Outros <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/plano" style="color: #599a80;">Planos <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/profissionais" style="color: #599a80;">Profissionais <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/balanco" style="color: #599a80;">Balanco <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="/outros/anual" style="background-color: #599a80;">- Anual <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/trimestral" style="color: #599a80;">- Trimestral <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/mensal" style="color: #599a80;">- Mensal <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/diario" style="color: #599a80;">- Diario <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/conta" style="color: #599a80;">Contas <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/caixa" style="color: #599a80;">Caixa <span class="sr-only">(current)</span></a>
                </li>
            </ul>
         </nav>
        </div>
    </div>
<main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3 main-fundo">
    <section class="row text-center placeholders">
        <div class="jumbotron busca">
            <div class="container">
                <div class="container">
                    <h3>Anual</h3>
                </div>
            </div>
        </div>
    </section>
</main>
        {% endblock %}

outro/templates/balanco.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar menu-lateral">
            <ul class="nav nav-pills flex-column">
                <li class="nav-item">
                    <a class="nav-link " href="/outros" style="color: #599a80;">Outros <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/plano" style="color: #599a80;">Planos <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/profissionais" style="color: #599a80;">Profissionais <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="/outros/balanco" style="background-color: #599a80;">Balanco <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/anual" style="color: #599a80;">- Anual <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/trimestral" style="color: #599a80;">- Trimestral <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/mensal" style="color: #599a80;">- Mensal <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/diario" style="color: #599a80;">- Diario <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/conta" style="color: #599a80;">Contas <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/caixa" style="color: #599a80;">Caixa <span class="sr-only">(current)</span></a>
                </li>
            </ul>
         </nav>
        </div>
    </div>
<main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3 main-fundo">
    <section class="row text-center placeholders">
        <div class="jumbotron busca">
            <div class="container">
                <div class="container">
                    <a class="link" href="/outros/anual"><img src="{% static '/img/anual.png' %}" /></a>
                    <a class="link" href="/outros/trimestral"><img src="{% static '/img/trimestral.png' %}" /></a>
                    <a class="link" href="/outros/mensal"><img src="{% static '/img/mensal.png' %}" /></a>
                    <a class="link" href="/outros/diario"><img src="{% static '/img/diario.png' %}" /></a>
                </div>
            </div>
        </div>
    </section>
</main>
        {% endblock %}

outro/templates/diario.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar menu-lateral">
            <ul class="nav nav-pills flex-column">
                <li class="nav-item">
                    <a class="nav-link " href="/outros" style="color: #599a80;">Outros <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/plano" style="color: #599a80;">Planos <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/profissionais" style="color: #599a80;">Profissionais <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/balanco" style="color: #599a80;">Balanco <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/anual" style="color: #599a80;">- Anual <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/trimestral" style="color: #599a80;">- Trimestral <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/mensal" style="color: #599a80;">- Mensal <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="/outros/diario" style="background-color: #599a80;">- Diario <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/conta" style="color: #599a80;">Contas <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/caixa" style="color: #599a80;">Caixa <span class="sr-only">(current)</span></a>
                </li>
            </ul>
         </nav>
        </div>
    </div>
<main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3 main-fundo">
    <section class="row text-center placeholders">
        <div class="jumbotron busca">
            <div class="container">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="row ">
                            <input type="date" class="form-control col-md-3 "  name="data">
                            &nbsp;&nbsp;&nbsp;<button type="submit" class="btn btn-primary " style="background-color: #599a80; border-color:#235440;">Buscar</button>
                        </div>
                    </form>
                    <div class="col-md-12 col-md-offset-3">
                        <table class="table">
                            <tr>
                                <th>ID</th>
                                <th>Data</th>
                                <th>Tipo</th>
                                <th>Descricao</th>
                                <th>Total</th>
                            </tr>
                            {% for caixa_geral in caixas %}
                            <tr>
                                <td>{{caixa_geral.id}}</td>
                                <td>{{caixa_geral.data}}</td>
                                <td>{{caixa_geral.get_tipo_display}}</td>
                                <td>{{caixa_geral.desc}}</td>
                                <td>{{caixa_geral.total}}</td>
                            </tr>
                            {% endfor %}
                        </table>
                        <button type="submit" class="btn btn-primary float-right" style="background-color: #599a80; border-color:#235440;">Imprimir</button>
                    </div>
            </div>
        </div>
    </section>
</main>
        {% endblock %}

outro/templates/mensal.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar menu-lateral">
            <ul class="nav nav-pills flex-column">
                <li class="nav-item">
                    <a class="nav-link " href="/outros" style="color: #599a80;">Outros <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/plano" style="color: #599a80;">Planos <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/profissionais" style="color: #599a80;">Profissionais <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/balanco" style="color: #599a80;">Balanco <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/anual" style="color: #599a80;">- Anual <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/trimestral" style="color: #599a80;">- Trimestral <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="/outros/mensal" style="background-color: #599a80;">- Mensal <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/diario" style="color: #599a80;">- Diario <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/conta" style="color: #599a80;">Contas <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/caixa" style="color: #599a80;">Caixa <span class="sr-only">(current)</span></a>
                </li>
            </ul>
         </nav>
        </div>
    </div>
<main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3 main-fundo">
    <section class="row text-center placeholders">
        <div class="jumbotron busca">
            <div class="container">
                <div class="container">
                    <input type="hidden" id="yFat" value="{{fat| stringformat:'d'}}" />
                    <input type="hidden" id="yCus" value="{{cus| stringformat:'d'}}" />
                    <input type="hidden" id="yLuc" value="{{luc| stringformat:'d'}}" />
                    <div id="chartContainer" style="height: 300px; width: 100%;">
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
<script type="text/javascript">
    yFat = Number(document.getElementById('yFat').value);
    yCus = Number(document.getElementById('yCus').value);
    yLuc = Number(document.getElementById('yLuc').value);
    window.onload = function () {
        var chart = new CanvasJS.Chart("chartContainer",
            {
                title:{
                text: "Balanco Mensal"
            },
            data: [
            {
                type: "column", //change type to bar, line, area, pie, etc
                dataPoints: [
                    { y: yFat, label: "Faturamento" },
                    { y: yLuc, label: "Lucro" },
                    { y: yCus, label: "Custo" },

                ]
            }
            ]
        });

    chart.render();
  }
  </script>
 <script type="text/javascript" src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
        {% endblock %}

outro/templates/outro.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar menu-lateral">
            <ul class="nav nav-pills flex-column">
                <li class="nav-item">
                    <a class="nav-link active" href="/outros" style="background-color: #599a80;">Outros <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/plano" style="color: #599a80;">Planos <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/profissionais" style="color: #599a80;">Profissionais <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/balanco" style="color: #599a80;">Balanco <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/conta" style="color: #599a80;">Contas <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/caixa" style="color: #599a80;">Caixa <span class="sr-only">(current)</span></a>
                </li>
            </ul>
         </nav>
        </div>
    </div>
<main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3 main-fundo">
    <section class="row text-center placeholders">
        <div class="jumbotron busca">
            <div class="container">
                <a class="link" href="/plano"><img src="{% static '/img/planos.png' %}" /></a>
                <a class="link" href="/outros/profissionais"><img src="{% static '/img/prof.png' %}" /></a>
                <a class="link" href="/outros/balanco"><img src="{% static '/img/balanco.png' %}" /></a>
                <a class="link" href="/conta"><img src="{% static '/img/contas.png' %}" /></a>
                <a class="link" href="/caixa"><img src="{% static '/img/caixa.png' %}" /></a>
            </div>
        </div>
    </section>
</main>
        {% endblock %}

outro/templates/trimestral.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar menu-lateral">
            <ul class="nav nav-pills flex-column">
                <li class="nav-item">
                    <a class="nav-link " href="/outros" style="color: #599a80;">Outros <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/plano" style="color: #599a80;">Planos <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/profissionais" style="color: #599a80;">Profissionais <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/balanco" style="color: #599a80;">Balanco <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/anual" style="color: #599a80;">- Anual <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="/outros/trimestral" style="background-color: #599a80;">- Trimestral <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/mensal" style="color: #599a80;">- Mensal <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/outros/diario" style="color: #599a80;">- Diario <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/conta" style="color: #599a80;">Contas <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="/caixa" style="color: #599a80;">Caixa <span class="sr-only">(current)</span></a>
                </li>
            </ul>
         </nav>
        </div>
    </div>
<main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3 main-fundo">
    <section class="row text-center placeholders">
        <div class="jumbotron busca">
            <div class="container">
                <div class="container">
                    <h3>Trimestral</h3>
                </div>
            </div>
        </div>
    </section>
</main>
        {% endblock %}